version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pokemon
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  pokemon-backend:
    container_name: pokemon-backend
    image: pokemon-backend
    build:
      context: ./
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: pokemon
      NODE_ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

  pokemon-frontend:
    container_name: pokemon-frontend
    image: pokemon-frontend
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    environment:
      API_URL: http://pokemon-backend:3000
    ports:
      - '80:4201'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
